version: "3.8"

services:
  spring:
    build: back
    container_name: spring
    restart: always
    expose:
      - "8081"
    volumes:
      - ./data:/app/data
    networks:
      - my_network
  nginx:
    build: front
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - analysis
    networks:
      - my_network
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    networks:
      - my_network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  analysis:
    build: core/analysis
    container_name: analysis
    restart: always
    volumes:
      - "./core/analysis/app:/app"
    expose:
      - "8082"
    networks:
      - my_network
    entrypoint: "gunicorn -k uvicorn.workers.UvicornWorker --access-logfile ./gunicorn-access.log main:app --bind 0.0.0.0:8082 --workers 2"

networks:
  my_network:
    driver: bridge
