version: "3.8"

services:
  spring:
    build: back
    container_name: spring
    restart: always
    expose:
      - "8081"
    volumes:
      - ./data:/app/data
    networks:
      - my_network
  core:
    build: core
    container_name: core
    restart: always
    volumes:
      - "./data:/app/data"
    expose:
      - "8082"
    networks:
      - my_network
    entrypoint: "gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8082 --workers 1"
  nginx:
    build: front
    container_name: nginx
    restart: unless-stopped
    # volumes:
    # - ./front/deploy/nginx:/etc/nginx/conf.d
    # - ./front/deploy/certbot/conf:/etc/letsencrypt
    # - ./front/deploy/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - core
    networks:
      - my_network
    command: '/bin/sh -c ''nginx -g "daemon off;" & while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    networks:
      - my_network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  my_network:
    driver: bridge
